language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

os:
    - linux

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - conda install --yes viennarna -c conda-forge -c bioconda
    - export CONDA_PATH=/home/travis/miniconda2/
    - export CONDA_LIB_PATH=/home/travis/miniconda2/lib
    - ls $CONDA_LIB_PATH
    - ls $CONDA_PATH/include
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_LIB_PATH
  
script:
    # go to build directory
    - cd $TRAVIS_BUILD_DIR 
    # generate autotools's files 
    - bash autotools-init.sh
    # configure and build 
    - ./configure --with-RNA=$CONDA_PATH --prefix=$HOME/ExpaRNA 
    - make && make install
    # call binary
    - $HOME/ExpaRNA/bin/ExpaRNA -h
